/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package pacmanprogram;

import java.awt.Color;
import java.awt.Font;
import java.util.ArrayList;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JTextField;

/**
 *
 * @author Kevin
 * @author ChanWoo
 */
public class GUI extends javax.swing.JFrame {
    /**
     * Creates new form GUI
     */
    
    static Game game = new Game();
    static New_Login login = new New_Login();
    static New_FileManagement fileManage = new New_FileManagement();
    static New_ProfileManagement profileManage = new New_ProfileManagement();
    static New_DataManagement dataManage = new New_DataManagement();
    static New_GetUserInfo getUserInfo = new New_GetUserInfo();
    static New_GetLoginInfoClass currentUserInfo;
//    static Login userInfoGetter = new Login();
    static String fileName = "UserData.txt";
    static String guestUsername = "Guest";
    static String guestPassword = "DefaultPassword";
    
//    private String newUsername;
//    private String newPassword;
//    private String newDisplayName;    
//    GetLoginInfoClass getinfo = new GetLoginInfoClass();
    
    public GUI() {
        initComponents();
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainMenuPanel = new javax.swing.JPanel();
        playGameButton = new javax.swing.JButton();
        goToLoginButton = new javax.swing.JButton();
        goToProfileButton = new javax.swing.JButton();
        mainMenuViewStatisticsButton = new javax.swing.JButton();
        PacmanImageLabel = new javax.swing.JLabel();
        gamePanel = game;
        topMenuButtonPanel = new javax.swing.JPanel();
        mainMenuButton = new javax.swing.JButton();
        playerLabel = new javax.swing.JLabel();
        nameDisplayLabel = new javax.swing.JLabel();
        logOutButton = new javax.swing.JButton();
        loginPanel = new javax.swing.JPanel();
        usernameField = new javax.swing.JTextField();
        usernameLabel = new java.awt.Label();
        passwordLabel = new java.awt.Label();
        loginSubmitButton = new javax.swing.JButton();
        noUsernameLabel = new javax.swing.JLabel();
        createProfileFromLoginButton = new javax.swing.JButton();
        loginStatusLabel = new javax.swing.JLabel();
        passwordField = new javax.swing.JPasswordField();
        profileManagementPanel = new javax.swing.JPanel();
        modifyProfileButton = new javax.swing.JButton();
        createProfileButton = new javax.swing.JButton();
        deleteProfileButton = new javax.swing.JButton();
        createProfilePanel = new javax.swing.JPanel();
        createUsernameField = new javax.swing.JTextField();
        createPasswordField = new javax.swing.JTextField();
        createPasswordCheckField = new javax.swing.JTextField();
        createSecurityQuestionField = new javax.swing.JTextField();
        createDisplayNameField = new javax.swing.JTextField();
        createUsernameLabel = new javax.swing.JLabel();
        createPasswordLabel = new javax.swing.JLabel();
        createPasswordCheckLabel = new javax.swing.JLabel();
        createSecurityQuestionLabel = new javax.swing.JLabel();
        createDisplayNameLabel = new javax.swing.JLabel();
        createProfileSubmitButton = new javax.swing.JButton();
        profileCreateStatusLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        createSecurityAnswerField = new javax.swing.JTextField();
        deleteProfilePanel = new javax.swing.JPanel();
        deleteUsernameLabel = new javax.swing.JLabel();
        deletePasswordLabel = new javax.swing.JLabel();
        deleteUsernameField = new javax.swing.JTextField();
        deleteSecurityQuestionLabel = new javax.swing.JLabel();
        profileDeleteButton = new javax.swing.JButton();
        deletePasswordField = new javax.swing.JTextField();
        profileDeleteStatusLabel = new javax.swing.JLabel();
        deleteProfileSecurityQuestionLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        deleteProfileSecurityAnswerField = new javax.swing.JTextField();
        statisticsPanel = new javax.swing.JTabbedPane();
        leaderboardPanel = new javax.swing.JPanel();
        leaderboardLabel = new javax.swing.JLabel();
        personalStatsPanel = new javax.swing.JPanel();
        personalStatsLabel = new javax.swing.JLabel();
        modificationPanel = new javax.swing.JPanel();
        changeDisplayNamePanelButton = new javax.swing.JButton();
        changePasswordPanelButton = new javax.swing.JButton();
        passwordChangePanel = new javax.swing.JPanel();
        passwordChangeUsernameLabel = new javax.swing.JLabel();
        passwordChangePasswordLabel = new javax.swing.JLabel();
        passwordChangeUsernameField = new javax.swing.JTextField();
        passwordChangePasswordField = new javax.swing.JTextField();
        passwordChangeNewPasswordLabel = new javax.swing.JLabel();
        passwordChangeNewPasswordField = new javax.swing.JTextField();
        passwordChangeButton = new javax.swing.JButton();
        changePasswordStatusLabel = new javax.swing.JLabel();
        displayNameChangePanel = new javax.swing.JPanel();
        displayNameChangeUsernameLabel = new javax.swing.JLabel();
        displayNameChangePasswordLabel = new javax.swing.JLabel();
        displayNameChangeDisplayNameLabel = new javax.swing.JLabel();
        displayNameChangePasswordField = new javax.swing.JTextField();
        jTextField14 = new javax.swing.JTextField();
        jTextField15 = new javax.swing.JTextField();
        displayNameChangeButton = new javax.swing.JButton();
        changeDNStatusLabel = new javax.swing.JLabel();
        gameSettingsPanel = new javax.swing.JPanel();
        levelSelectionLabel = new javax.swing.JLabel();
        levelSelectionField = new javax.swing.JTextField();
        startGameButton = new javax.swing.JButton();
        maxLevelReachedLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(400, 10, 448, 656));
        setMinimumSize(new java.awt.Dimension(448, 690));
        setPreferredSize(new java.awt.Dimension(448, 690));

        makeAllPanelsNotVisible();
        setButtonsVisibility();
        mainMenuPanel.setVisible(true);
        mainMenuPanel.setBackground(new java.awt.Color(0, 0, 0));

        playGameButton.setText("Play Game");
        playGameButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playGameButtonActionPerformed(evt);
            }
        });

        goToLoginButton.setText("Login");
        goToLoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goToLoginButtonActionPerformed(evt);
            }
        });

        goToProfileButton.setText("Profile Management");
        goToProfileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goToProfileButtonActionPerformed(evt);
            }
        });

        mainMenuViewStatisticsButton.setText("View Statistics");
        mainMenuViewStatisticsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainMenuViewStatisticsButtonActionPerformed(evt);
            }
        });

        PacmanImageLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pacmanprogram/image.png"))); // NOI18N

        javax.swing.GroupLayout mainMenuPanelLayout = new javax.swing.GroupLayout(mainMenuPanel);
        mainMenuPanel.setLayout(mainMenuPanelLayout);
        mainMenuPanelLayout.setHorizontalGroup(
            mainMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainMenuPanelLayout.createSequentialGroup()
                .addGroup(mainMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainMenuPanelLayout.createSequentialGroup()
                        .addGap(165, 165, 165)
                        .addComponent(playGameButton))
                    .addGroup(mainMenuPanelLayout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(PacmanImageLabel))
                    .addGroup(mainMenuPanelLayout.createSequentialGroup()
                        .addGap(180, 180, 180)
                        .addComponent(goToLoginButton))
                    .addGroup(mainMenuPanelLayout.createSequentialGroup()
                        .addGap(137, 137, 137)
                        .addComponent(goToProfileButton))
                    .addGroup(mainMenuPanelLayout.createSequentialGroup()
                        .addGap(156, 156, 156)
                        .addComponent(mainMenuViewStatisticsButton)))
                .addGap(100, 100, 100))
        );
        mainMenuPanelLayout.setVerticalGroup(
            mainMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainMenuPanelLayout.createSequentialGroup()
                .addComponent(PacmanImageLabel)
                .addGap(52, 52, 52)
                .addComponent(playGameButton)
                .addGap(32, 32, 32)
                .addComponent(goToLoginButton)
                .addGap(28, 28, 28)
                .addComponent(goToProfileButton)
                .addGap(28, 28, 28)
                .addComponent(mainMenuViewStatisticsButton)
                .addContainerGap(272, Short.MAX_VALUE))
        );

        game.endGame();
        gamePanel.setBackground(new java.awt.Color(0, 0, 0));
        gamePanel.setEnabled(false);
        gamePanel.setMaximumSize(new java.awt.Dimension(448, 576));
        gamePanel.setMinimumSize(new java.awt.Dimension(224, 288));
        gamePanel.setPreferredSize(new java.awt.Dimension(448, 576));

        javax.swing.GroupLayout gamePanelLayout = new javax.swing.GroupLayout(gamePanel);
        gamePanel.setLayout(gamePanelLayout);
        gamePanelLayout.setHorizontalGroup(
            gamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 448, Short.MAX_VALUE)
        );
        gamePanelLayout.setVerticalGroup(
            gamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 576, Short.MAX_VALUE)
        );

        topMenuButtonPanel.setMaximumSize(new java.awt.Dimension(448, 80));
        topMenuButtonPanel.setMinimumSize(new java.awt.Dimension(224, 40));
        topMenuButtonPanel.setPreferredSize(new java.awt.Dimension(448, 80));

        mainMenuButton.setText("Menu");
        mainMenuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainMenuButtonActionPerformed(evt);
            }
        });

        playerLabel.setText("Player:");

        nameDisplayLabel.setText("Guest");

        logOutButton.setText("Log Out");
        logOutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logOutButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout topMenuButtonPanelLayout = new javax.swing.GroupLayout(topMenuButtonPanel);
        topMenuButtonPanel.setLayout(topMenuButtonPanelLayout);
        topMenuButtonPanelLayout.setHorizontalGroup(
            topMenuButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topMenuButtonPanelLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(mainMenuButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                .addComponent(logOutButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(playerLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nameDisplayLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );
        topMenuButtonPanelLayout.setVerticalGroup(
            topMenuButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, topMenuButtonPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(topMenuButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mainMenuButton)
                    .addComponent(playerLabel)
                    .addComponent(nameDisplayLabel)
                    .addComponent(logOutButton))
                .addGap(26, 26, 26))
        );

        loginPanel.setPreferredSize(new java.awt.Dimension(428, 576));

        usernameLabel.setText("Username:");

        passwordLabel.setText("Password: ");

        loginSubmitButton.setText("Submit");
        loginSubmitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginSubmitButtonActionPerformed(evt);
            }
        });

        noUsernameLabel.setText("Don't have a username?");

        createProfileFromLoginButton.setText("Create Profile");
        createProfileFromLoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createProfileFromLoginButtonActionPerformed(evt);
            }
        });

        loginStatusLabel.setText("Login Status");

        javax.swing.GroupLayout loginPanelLayout = new javax.swing.GroupLayout(loginPanel);
        loginPanel.setLayout(loginPanelLayout);
        loginPanelLayout.setHorizontalGroup(
            loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginPanelLayout.createSequentialGroup()
                .addContainerGap(108, Short.MAX_VALUE)
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginPanelLayout.createSequentialGroup()
                        .addComponent(noUsernameLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(createProfileFromLoginButton))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginPanelLayout.createSequentialGroup()
                        .addComponent(passwordLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(loginPanelLayout.createSequentialGroup()
                                .addComponent(loginSubmitButton)
                                .addGap(175, 175, 175))
                            .addComponent(passwordField)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginPanelLayout.createSequentialGroup()
                        .addComponent(usernameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(loginStatusLabel)
                            .addComponent(usernameField, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(49, 49, 49))
        );
        loginPanelLayout.setVerticalGroup(
            loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginPanelLayout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addComponent(loginStatusLabel)
                .addGap(18, 18, 18)
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(usernameField, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(usernameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(loginPanelLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(passwordLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(loginPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(86, 86, 86)
                .addComponent(loginSubmitButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 181, Short.MAX_VALUE)
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(noUsernameLabel)
                    .addComponent(createProfileFromLoginButton))
                .addGap(91, 91, 91))
        );

        passwordLabel.getAccessibleContext().setAccessibleName("Password:");

        modifyProfileButton.setText("Modify Profile");
        modifyProfileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifyProfileButtonActionPerformed(evt);
            }
        });

        createProfileButton.setText("Create Profile");
        createProfileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createProfileButtonActionPerformed(evt);
            }
        });

        deleteProfileButton.setText("Delete Profile");
        deleteProfileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteProfileButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout profileManagementPanelLayout = new javax.swing.GroupLayout(profileManagementPanel);
        profileManagementPanel.setLayout(profileManagementPanelLayout);
        profileManagementPanelLayout.setHorizontalGroup(
            profileManagementPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(profileManagementPanelLayout.createSequentialGroup()
                .addGap(158, 158, 158)
                .addGroup(profileManagementPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(modifyProfileButton)
                    .addComponent(deleteProfileButton)
                    .addComponent(createProfileButton))
                .addContainerGap(216, Short.MAX_VALUE))
        );
        profileManagementPanelLayout.setVerticalGroup(
            profileManagementPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(profileManagementPanelLayout.createSequentialGroup()
                .addGap(126, 126, 126)
                .addComponent(createProfileButton)
                .addGap(37, 37, 37)
                .addComponent(modifyProfileButton)
                .addGap(40, 40, 40)
                .addComponent(deleteProfileButton)
                .addContainerGap(332, Short.MAX_VALUE))
        );

        createUsernameLabel.setText("Username");

        createPasswordLabel.setText("Password");

        createPasswordCheckLabel.setText("Re-enter Password");

        createSecurityQuestionLabel.setText("Security Question");

        createDisplayNameLabel.setText("Display Name");

        createProfileSubmitButton.setText("Submit");
        createProfileSubmitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createProfileSubmitButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("Security Answer");

        javax.swing.GroupLayout createProfilePanelLayout = new javax.swing.GroupLayout(createProfilePanel);
        createProfilePanel.setLayout(createProfilePanelLayout);
        createProfilePanelLayout.setHorizontalGroup(
            createProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, createProfilePanelLayout.createSequentialGroup()
                .addContainerGap(58, Short.MAX_VALUE)
                .addGroup(createProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(createProfilePanelLayout.createSequentialGroup()
                        .addComponent(createPasswordCheckLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(createPasswordCheckField, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(createProfilePanelLayout.createSequentialGroup()
                        .addComponent(createPasswordLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(createPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(createProfilePanelLayout.createSequentialGroup()
                        .addComponent(createDisplayNameLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(createProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(createProfileSubmitButton)
                            .addComponent(createDisplayNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(createProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(profileCreateStatusLabel)
                        .addGroup(createProfilePanelLayout.createSequentialGroup()
                            .addComponent(createUsernameLabel)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(createUsernameField, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(createProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(createProfilePanelLayout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addGap(18, 18, 18)
                            .addComponent(createSecurityAnswerField))
                        .addGroup(createProfilePanelLayout.createSequentialGroup()
                            .addComponent(createSecurityQuestionLabel)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(createSecurityQuestionField, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(104, 104, 104))
        );
        createProfilePanelLayout.setVerticalGroup(
            createProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(createProfilePanelLayout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addComponent(profileCreateStatusLabel)
                .addGap(28, 28, 28)
                .addGroup(createProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(createUsernameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(createUsernameLabel))
                .addGap(28, 28, 28)
                .addGroup(createProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(createPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(createPasswordLabel))
                .addGap(29, 29, 29)
                .addGroup(createProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(createPasswordCheckField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(createPasswordCheckLabel))
                .addGap(26, 26, 26)
                .addGroup(createProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(createSecurityQuestionField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(createSecurityQuestionLabel))
                .addGap(18, 18, 18)
                .addGroup(createProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(createSecurityAnswerField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(createProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(createDisplayNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(createDisplayNameLabel))
                .addGap(18, 18, 18)
                .addComponent(createProfileSubmitButton)
                .addContainerGap(204, Short.MAX_VALUE))
        );

        deleteUsernameLabel.setText("Username:");

        deletePasswordLabel.setText("Password:");

        deleteSecurityQuestionLabel.setText("Security Question:");

        profileDeleteButton.setText("Delete Profile!");
        profileDeleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profileDeleteButtonActionPerformed(evt);
            }
        });

        profileDeleteStatusLabel.setText("Status");

        jLabel2.setText("Answer");

        deleteProfileSecurityAnswerField.setText("jTextField1");

        javax.swing.GroupLayout deleteProfilePanelLayout = new javax.swing.GroupLayout(deleteProfilePanel);
        deleteProfilePanel.setLayout(deleteProfilePanelLayout);
        deleteProfilePanelLayout.setHorizontalGroup(
            deleteProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(deleteProfilePanelLayout.createSequentialGroup()
                .addContainerGap(81, Short.MAX_VALUE)
                .addGroup(deleteProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, deleteProfilePanelLayout.createSequentialGroup()
                        .addGroup(deleteProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(deleteProfilePanelLayout.createSequentialGroup()
                                .addComponent(deleteUsernameLabel)
                                .addGap(18, 18, 18)
                                .addComponent(deleteUsernameField, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(deleteProfilePanelLayout.createSequentialGroup()
                                .addGroup(deleteProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, deleteProfilePanelLayout.createSequentialGroup()
                                        .addGroup(deleteProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(deletePasswordLabel)
                                            .addComponent(deleteSecurityQuestionLabel))
                                        .addGap(18, 18, 18))
                                    .addGroup(deleteProfilePanelLayout.createSequentialGroup()
                                        .addGap(45, 45, 45)
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGroup(deleteProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(profileDeleteButton)
                                    .addComponent(deletePasswordField, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                                    .addComponent(deleteProfileSecurityQuestionLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(deleteProfileSecurityAnswerField))))
                        .addGap(121, 121, 121))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, deleteProfilePanelLayout.createSequentialGroup()
                        .addComponent(profileDeleteStatusLabel)
                        .addGap(204, 204, 204))))
        );
        deleteProfilePanelLayout.setVerticalGroup(
            deleteProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(deleteProfilePanelLayout.createSequentialGroup()
                .addGap(115, 115, 115)
                .addComponent(profileDeleteStatusLabel)
                .addGap(28, 28, 28)
                .addGroup(deleteProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deleteUsernameLabel)
                    .addComponent(deleteUsernameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(deleteProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deletePasswordLabel)
                    .addComponent(deletePasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(deleteProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deleteSecurityQuestionLabel)
                    .addComponent(deleteProfileSecurityQuestionLabel))
                .addGap(29, 29, 29)
                .addGroup(deleteProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(deleteProfileSecurityAnswerField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addComponent(profileDeleteButton)
                .addContainerGap(195, Short.MAX_VALUE))
        );

        leaderboardLabel.setText("jLabel1");

        javax.swing.GroupLayout leaderboardPanelLayout = new javax.swing.GroupLayout(leaderboardPanel);
        leaderboardPanel.setLayout(leaderboardPanelLayout);
        leaderboardPanelLayout.setHorizontalGroup(
            leaderboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leaderboardPanelLayout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addComponent(leaderboardLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
        );
        leaderboardPanelLayout.setVerticalGroup(
            leaderboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leaderboardPanelLayout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(leaderboardLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 432, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(54, Short.MAX_VALUE))
        );

        statisticsPanel.addTab("Leaderboard", leaderboardPanel);

        javax.swing.GroupLayout personalStatsPanelLayout = new javax.swing.GroupLayout(personalStatsPanel);
        personalStatsPanel.setLayout(personalStatsPanelLayout);
        personalStatsPanelLayout.setHorizontalGroup(
            personalStatsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(personalStatsPanelLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(personalStatsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(89, Short.MAX_VALUE))
        );
        personalStatsPanelLayout.setVerticalGroup(
            personalStatsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(personalStatsPanelLayout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(personalStatsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(242, Short.MAX_VALUE))
        );

        statisticsPanel.addTab("Personal Stats", personalStatsPanel);

        changeDisplayNamePanelButton.setText("Change Display Name");
        changeDisplayNamePanelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeDisplayNamePanelButtonActionPerformed(evt);
            }
        });

        changePasswordPanelButton.setText("Change Password");
        changePasswordPanelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changePasswordPanelButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout modificationPanelLayout = new javax.swing.GroupLayout(modificationPanel);
        modificationPanel.setLayout(modificationPanelLayout);
        modificationPanelLayout.setHorizontalGroup(
            modificationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(modificationPanelLayout.createSequentialGroup()
                .addGroup(modificationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(modificationPanelLayout.createSequentialGroup()
                        .addGap(142, 142, 142)
                        .addComponent(changePasswordPanelButton))
                    .addGroup(modificationPanelLayout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addComponent(changeDisplayNamePanelButton)))
                .addContainerGap(151, Short.MAX_VALUE))
        );
        modificationPanelLayout.setVerticalGroup(
            modificationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(modificationPanelLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(changePasswordPanelButton)
                .addGap(48, 48, 48)
                .addComponent(changeDisplayNamePanelButton)
                .addContainerGap(237, Short.MAX_VALUE))
        );

        passwordChangeUsernameLabel.setText("Username:");

        passwordChangePasswordLabel.setText("Password:");

        passwordChangeNewPasswordLabel.setText("New Password:");

        passwordChangeButton.setText("Change Password");
        passwordChangeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordChangeButtonActionPerformed(evt);
            }
        });

        changePasswordStatusLabel.setText("Status");

        javax.swing.GroupLayout passwordChangePanelLayout = new javax.swing.GroupLayout(passwordChangePanel);
        passwordChangePanel.setLayout(passwordChangePanelLayout);
        passwordChangePanelLayout.setHorizontalGroup(
            passwordChangePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(passwordChangePanelLayout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(passwordChangePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(passwordChangeNewPasswordLabel)
                    .addComponent(passwordChangeUsernameLabel)
                    .addComponent(passwordChangePasswordLabel))
                .addGap(18, 18, 18)
                .addGroup(passwordChangePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(passwordChangeButton)
                    .addGroup(passwordChangePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(passwordChangeUsernameField)
                        .addComponent(passwordChangePasswordField)
                        .addComponent(passwordChangeNewPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(83, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, passwordChangePanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(changePasswordStatusLabel)
                .addGap(198, 198, 198))
        );
        passwordChangePanelLayout.setVerticalGroup(
            passwordChangePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(passwordChangePanelLayout.createSequentialGroup()
                .addContainerGap(90, Short.MAX_VALUE)
                .addComponent(changePasswordStatusLabel)
                .addGap(18, 18, 18)
                .addGroup(passwordChangePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passwordChangeUsernameLabel)
                    .addComponent(passwordChangeUsernameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(passwordChangePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passwordChangePasswordLabel)
                    .addComponent(passwordChangePasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(passwordChangePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passwordChangeNewPasswordLabel)
                    .addComponent(passwordChangeNewPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addComponent(passwordChangeButton)
                .addGap(54, 54, 54))
        );

        displayNameChangeUsernameLabel.setText("Username:");

        displayNameChangePasswordLabel.setText("Password:");

        displayNameChangeDisplayNameLabel.setText("New Display Name:");

        displayNameChangeButton.setText("Change Display Name");
        displayNameChangeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayNameChangeButtonActionPerformed(evt);
            }
        });

        changeDNStatusLabel.setText("Status");

        javax.swing.GroupLayout displayNameChangePanelLayout = new javax.swing.GroupLayout(displayNameChangePanel);
        displayNameChangePanel.setLayout(displayNameChangePanelLayout);
        displayNameChangePanelLayout.setHorizontalGroup(
            displayNameChangePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(displayNameChangePanelLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(displayNameChangePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(displayNameChangeDisplayNameLabel)
                    .addComponent(displayNameChangePasswordLabel)
                    .addComponent(displayNameChangeUsernameLabel))
                .addGap(18, 18, 18)
                .addGroup(displayNameChangePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(changeDNStatusLabel)
                    .addComponent(displayNameChangeButton)
                    .addGroup(displayNameChangePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jTextField14)
                        .addComponent(displayNameChangePasswordField)
                        .addComponent(jTextField15, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(122, Short.MAX_VALUE))
        );
        displayNameChangePanelLayout.setVerticalGroup(
            displayNameChangePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, displayNameChangePanelLayout.createSequentialGroup()
                .addContainerGap(77, Short.MAX_VALUE)
                .addComponent(changeDNStatusLabel)
                .addGap(44, 44, 44)
                .addGroup(displayNameChangePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(displayNameChangeUsernameLabel)
                    .addComponent(jTextField14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(displayNameChangePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(displayNameChangePanelLayout.createSequentialGroup()
                        .addGroup(displayNameChangePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(displayNameChangePasswordLabel)
                            .addComponent(displayNameChangePasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(42, 42, 42))
                    .addGroup(displayNameChangePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextField15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(displayNameChangeDisplayNameLabel)))
                .addGap(58, 58, 58)
                .addComponent(displayNameChangeButton)
                .addGap(53, 53, 53))
        );

        levelSelectionLabel.setText("Enter the level you would like to start at:");

        levelSelectionField.setToolTipText("");

        startGameButton.setText("Start");
        startGameButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startGameButtonActionPerformed(evt);
            }
        });

        maxLevelReachedLabel.setText("jLabel1");

        javax.swing.GroupLayout gameSettingsPanelLayout = new javax.swing.GroupLayout(gameSettingsPanel);
        gameSettingsPanel.setLayout(gameSettingsPanelLayout);
        gameSettingsPanelLayout.setHorizontalGroup(
            gameSettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gameSettingsPanelLayout.createSequentialGroup()
                .addGroup(gameSettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(gameSettingsPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(levelSelectionLabel)
                        .addGap(18, 18, 18)
                        .addComponent(levelSelectionField, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(gameSettingsPanelLayout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addComponent(startGameButton))
                    .addGroup(gameSettingsPanelLayout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(maxLevelReachedLabel)))
                .addContainerGap(69, Short.MAX_VALUE))
        );
        gameSettingsPanelLayout.setVerticalGroup(
            gameSettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gameSettingsPanelLayout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addComponent(maxLevelReachedLabel)
                .addGap(18, 18, 18)
                .addGroup(gameSettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(levelSelectionLabel)
                    .addComponent(levelSelectionField, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(92, 92, 92)
                .addComponent(startGameButton)
                .addContainerGap(273, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(topMenuButtonPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(gamePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(loginPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 475, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(mainMenuPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(profileManagementPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(createProfilePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(deleteProfilePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(statisticsPanel)
                    .addContainerGap()))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 39, Short.MAX_VALUE)
                    .addComponent(modificationPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(0, 39, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 29, Short.MAX_VALUE)
                    .addComponent(passwordChangePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 29, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 20, Short.MAX_VALUE)
                    .addComponent(displayNameChangePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 19, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(59, 59, 59)
                    .addComponent(gameSettingsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(59, 59, 59)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(topMenuButtonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(gamePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(43, 43, 43)
                    .addComponent(loginPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 604, Short.MAX_VALUE)
                    .addGap(43, 43, 43)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(43, 43, 43)
                    .addComponent(mainMenuPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(43, 43, 43)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(43, 43, 43)
                    .addComponent(profileManagementPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(43, 43, 43)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(43, 43, 43)
                    .addComponent(createProfilePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(43, 43, 43)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(43, 43, 43)
                    .addComponent(deleteProfilePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(43, 43, 43)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(57, 57, 57)
                    .addComponent(statisticsPanel)
                    .addGap(57, 57, 57)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 150, Short.MAX_VALUE)
                    .addComponent(modificationPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(0, 150, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 180, Short.MAX_VALUE)
                    .addComponent(passwordChangePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 180, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 163, Short.MAX_VALUE)
                    .addComponent(displayNameChangePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 162, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(77, 77, 77)
                    .addComponent(gameSettingsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(78, 78, 78)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mainMenuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainMenuButtonActionPerformed

        if(currentUserInfo.GetUserName().equals(guestUsername)||!gamePanel.isVisible()){
            game.endGame();
        }
        else{
            int scoreToAdd = game.endGame();
            int levelReached = game.level.getLevel();
            dataManage.AddNewScore(currentUserInfo.GetUserName(),scoreToAdd,fileName);
            dataManage.AddNewMaxLevel(currentUserInfo.GetUserName(), levelReached, fileName);
        }
        makeAllPanelsNotVisible();
        mainMenuPanel.setVisible(true);
        setButtonsVisibility();
        updateJLabels();
        

    }//GEN-LAST:event_mainMenuButtonActionPerformed

    private void loginSubmitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginSubmitButtonActionPerformed

        String username = usernameField.getText();
        String password = passwordField.getText();
        currentUserInfo=login.login(username,password,fileName);
        updateJLabels();
        if (nameDisplayLabel.getText().equals("Guest")){
            loginStatusLabel.setText("Login Failed. Try again");
        }
        else {
            loginStatusLabel.setText("Login successful");
            makeAllPanelsNotVisible();
            mainMenuPanel.setVisible(true);
        }
        
        clearAllTextFields();
        setButtonsVisibility();
        
        
        
    }//GEN-LAST:event_loginSubmitButtonActionPerformed

    private void playGameButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playGameButtonActionPerformed

        if(currentUserInfo.GetUserName().equals(guestUsername)){
            makeAllPanelsNotVisible();
            game.startGame(1);
            gamePanel.setVisible(true);
            gamePanel.requestFocus();
            gamePanel.setEnabled(true);
            setButtonsVisibility();
        }
        
        else{
            makeAllPanelsNotVisible();
            gameSettingsPanel.setVisible(true);
            setButtonsVisibility();
        }
    }//GEN-LAST:event_playGameButtonActionPerformed

    private void goToLoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goToLoginButtonActionPerformed

        game.endGame();
        makeAllPanelsNotVisible();
        loginPanel.setVisible(true);
        setButtonsVisibility();
        
      
    }//GEN-LAST:event_goToLoginButtonActionPerformed

    private void goToProfileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goToProfileButtonActionPerformed
        game.endGame();
        makeAllPanelsNotVisible();
        profileManagementPanel.setVisible(true);        
        setButtonsVisibility();

    }//GEN-LAST:event_goToProfileButtonActionPerformed

    private void deleteProfileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteProfileButtonActionPerformed
        makeAllPanelsNotVisible();
        deleteProfilePanel.setVisible(true);
        deleteProfileSecurityQuestionLabel.setText(currentUserInfo.GetSecurityQuestion());
        setButtonsVisibility();

    }//GEN-LAST:event_deleteProfileButtonActionPerformed

    private void createProfileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createProfileButtonActionPerformed
        
        game.endGame();
        makeAllPanelsNotVisible();
        createProfilePanel.setVisible(true);
        setButtonsVisibility();

    }//GEN-LAST:event_createProfileButtonActionPerformed

    private void createProfileFromLoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createProfileFromLoginButtonActionPerformed
        game.endGame();
        makeAllPanelsNotVisible();
        createProfilePanel.setVisible(true);
        setButtonsVisibility();
        
    }//GEN-LAST:event_createProfileFromLoginButtonActionPerformed

    private void createProfileSubmitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createProfileSubmitButtonActionPerformed
        setButtonsVisibility();
        String newUsername = createUsernameField.getText();
        String newPassword = createPasswordField.getText();
        String passwordCheck = createPasswordCheckField.getText();
        String newSecurityQuestion = createSecurityQuestionField.getText();
        String newSecurityAnswer = createSecurityAnswerField.getText();
        String newDisplayName = createDisplayNameField.getText();

        
        if(!newPassword.equals(passwordCheck)){
            profileCreateStatusLabel.setText("The 're-enter' field does not match the password field");
        }
        
        else{
        
            profileManage.create(newUsername, newPassword, newDisplayName, newSecurityQuestion, newSecurityAnswer, fileName);
            profileCreateStatusLabel.setText("Profile is created");

            clearAllTextFields();
        }

        
    }//GEN-LAST:event_createProfileSubmitButtonActionPerformed

    private void profileDeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profileDeleteButtonActionPerformed
        // TODO add your handling code here:
        String username = deleteUsernameField.getText();
        String password = deletePasswordField.getText();
        String answer = deleteProfileSecurityAnswerField.getText();
        
        
        if(nameDisplayLabel.getText().equals("Guest")){
            profileDeleteStatusLabel.setText("Login Please");
        }
        else if(username.equals(currentUserInfo.GetUserName())&&password.equals(currentUserInfo.GetPassWord())&&answer.equals(currentUserInfo.GetSecurityAnswer())){
            profileManage.remove(username,password,answer,fileName);
            profileDeleteStatusLabel.setText("Profile is deleted");
            currentUserInfo=login.login("Guest","DefaultPassword","UserData.txt");
        }
        else if (!username.equals(currentUserInfo.GetUserName())) {
            profileDeleteStatusLabel.setText("Warning: Delete your own profile");
        }
        else if (username.equals(currentUserInfo.GetUserName())&&!password.equals(currentUserInfo.GetPassWord())) {
            profileDeleteStatusLabel.setText("Password is incorrect. Try again.");
        }
        else if (username.equals(currentUserInfo.GetUserName())&&password.equals(currentUserInfo.GetPassWord())&&!answer.equals(currentUserInfo.GetSecurityQuestion())) {
            profileDeleteStatusLabel.setText("Security answer is incorrect. Try again.");
        }
        clearAllTextFields();
        
        updateJLabels();
        setButtonsVisibility();
    }//GEN-LAST:event_profileDeleteButtonActionPerformed

    private void modifyProfileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifyProfileButtonActionPerformed
        game.endGame();
        makeAllPanelsNotVisible();
        setButtonsVisibility();
        modificationPanel.setVisible(true);
        
    }//GEN-LAST:event_modifyProfileButtonActionPerformed

    private void mainMenuViewStatisticsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainMenuViewStatisticsButtonActionPerformed
        makeAllPanelsNotVisible();
        setButtonsVisibility();
        statisticsPanel.setVisible(true);
        
        updateJLabels();
        
    }//GEN-LAST:event_mainMenuViewStatisticsButtonActionPerformed

    private void changePasswordPanelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changePasswordPanelButtonActionPerformed
        // TODO add your handling code here:
        game.endGame();
        makeAllPanelsNotVisible();
        setButtonsVisibility();
        passwordChangePanel.setVisible(true);

    }//GEN-LAST:event_changePasswordPanelButtonActionPerformed

    private void changeDisplayNamePanelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeDisplayNamePanelButtonActionPerformed
        // TODO add your handling code here:
        game.endGame();
        makeAllPanelsNotVisible();
        setButtonsVisibility();
        displayNameChangePanel.setVisible(true);

    }//GEN-LAST:event_changeDisplayNamePanelButtonActionPerformed

    private void passwordChangeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordChangeButtonActionPerformed
        // TODO add your handling code here:
        String username = passwordChangeUsernameField.getText();
        String password = passwordChangePasswordField.getText();
        String newPassword = passwordChangeNewPasswordField.getText();
        if(nameDisplayLabel.getText().equals("Guest")){
            changePasswordStatusLabel.setText("Login Please");
        }
        else if(username.equals(currentUserInfo.GetUserName())&&password.equals(currentUserInfo.GetPassWord())){
            profileManage.ChangePW(username, password, newPassword, fileName);
            changePasswordStatusLabel.setText("Password is changed");
        }
        else {
            changePasswordStatusLabel.setText("Password Change is failed. Try again");
        }
        
        clearAllTextFields();       
    }//GEN-LAST:event_passwordChangeButtonActionPerformed

    private void displayNameChangeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayNameChangeButtonActionPerformed
        // TODO add your handling code here:
        String username = jTextField14.getText();
        String password = displayNameChangePasswordField.getText();
        String newDisplayName = jTextField15.getText();
        if(nameDisplayLabel.getText().equals("Guest")){
            changeDNStatusLabel.setText("Login Please");
        }
        else if(username.equals(currentUserInfo.GetUserName())&&password.equals(currentUserInfo.GetPassWord())){
            profileManage.ChangeDN(username, password, newDisplayName, fileName);
            changeDNStatusLabel.setText("Display Name is changed");
        }
        else {
            changeDNStatusLabel.setText("Display Name Change is failed. Try again");
        }
        
        clearAllTextFields();
    }//GEN-LAST:event_displayNameChangeButtonActionPerformed

    private void logOutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logOutButtonActionPerformed
        currentUserInfo=login.login("Guest","DefaultPassword","UserData.txt");
        updateJLabels();
        setButtonsVisibility();
    }//GEN-LAST:event_logOutButtonActionPerformed

    private void startGameButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startGameButtonActionPerformed

            //this is where the game should start at the level specified by the user
            String levelSelection = levelSelectionField.getText();
            int levelSelectionAsInteger = Integer.parseInt(levelSelection);
            
            if(levelSelectionAsInteger>currentUserInfo.GetMaxLevel()){
                maxLevelReachedLabel.setText("You haven't unlocked level " + levelSelection);
            }
            
            else{
                makeAllPanelsNotVisible();
                game.startGame(levelSelectionAsInteger);
                gamePanel.setVisible(true);
                gamePanel.requestFocus();
                gamePanel.setEnabled(true);
                setButtonsVisibility();
            }
    }//GEN-LAST:event_startGameButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        fileManage.Initialize(fileName);
        currentUserInfo=login.login(guestUsername,guestPassword,fileName);
        
        
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
           

        
    }
    
    
   /**
    * This method sets all the panels invisible except the current panel that
    * the user is using.
    */
    public void makeAllPanelsNotVisible(){
        gamePanel.setVisible(false);
        mainMenuPanel.setVisible(false);
        loginPanel.setVisible(false);
        profileManagementPanel.setVisible(false);
        createProfilePanel.setVisible(false);
        deleteProfilePanel.setVisible(false);
        statisticsPanel.setVisible(false);
        modificationPanel.setVisible(false);
        passwordChangePanel.setVisible(false);
        displayNameChangePanel.setVisible(false);
        gameSettingsPanel.setVisible(false);
    }
    
    /**
     * This methods sets the visibility of "logOutButton"
     * The "logOutButton" is visible only if a user is logged in.
     */
    public void setButtonsVisibility(){
        if(gamePanel.isVisible()||gameSettingsPanel.isVisible()||currentUserInfo.GetUserName().equals("Guest")){
            logOutButton.setVisible(false);
        }
        
        else{
            logOutButton.setVisible(true);
        }
        
    }
    
    
    
    public void updateJLabels(){
        
        String personalStats = new String();
        String leaderboardStats = new String();
        ArrayList<New_TopScores> top10Leaderboard;
        top10Leaderboard = dataManage.GetTop10Score(fileName);
        
        currentUserInfo=login.login(currentUserInfo.GetUserName(), currentUserInfo.GetPassWord(), fileName);
        
        nameDisplayLabel.setText(currentUserInfo.GetUserName());
        
        if(currentUserInfo.GetUserName().equals(guestUsername)){
            personalStats="You are not logged in, so you cannot view personal stats";
        }
        
        else{
            int loopCounter;
            for(loopCounter=0;loopCounter<10;loopCounter++){
                personalStats+=currentUserInfo.GetScore(loopCounter)+"<br>";
                System.out.println(currentUserInfo.GetScore(loopCounter));
            }
        }
        
        personalStatsLabel.setText("<html>" + personalStats + "<html>");
        
        int loopCounter;
            for(loopCounter=0;loopCounter<10;loopCounter++){
                if(!top10Leaderboard.get(loopCounter).GetPlayer().equals(guestUsername)){
                    leaderboardStats+=top10Leaderboard.get(loopCounter).GetPlayer();
                    leaderboardStats+=" ";
                    leaderboardStats+=top10Leaderboard.get(loopCounter).GetScore()+"<br>";
                }
            }
            
        leaderboardLabel.setText("<html>" + leaderboardStats + "<html>");
        
        
        
        int maxLevelReached=currentUserInfo.GetMaxLevel();
        
        maxLevelReachedLabel.setText("You previously unlocked level " + maxLevelReached);
        
        
    }
    
    
    /**
     * For all the data & profile handling panels, if user fills in the text fields with informations
     * and click the button for submission, this method is called and clears the all text fields that
     * are placed on current panel.
     */
    public void clearAllTextFields(){
        
    createUsernameField.setText("");
    deletePasswordField.setText("");
    deleteProfileSecurityAnswerField.setText("");
    passwordChangeNewPasswordField.setText("");
    displayNameChangePasswordField.setText("");
    jTextField14.setText("");
    jTextField15.setText("");
    passwordChangeUsernameField.setText("");
    createPasswordField.setText("");
    createPasswordCheckField.setText("");
    createSecurityQuestionField.setText("");
    createSecurityAnswerField.setText("");
    createDisplayNameField.setText("");
    passwordChangePasswordField.setText("");
    deleteUsernameField.setText("");
    usernameField.setText("");
    passwordField.setText("");
    levelSelectionField.setText("");
    
    
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel PacmanImageLabel;
    private javax.swing.JLabel changeDNStatusLabel;
    private javax.swing.JButton changeDisplayNamePanelButton;
    private javax.swing.JButton changePasswordPanelButton;
    private javax.swing.JLabel changePasswordStatusLabel;
    private javax.swing.JTextField createDisplayNameField;
    private javax.swing.JLabel createDisplayNameLabel;
    private javax.swing.JTextField createPasswordCheckField;
    private javax.swing.JLabel createPasswordCheckLabel;
    private javax.swing.JTextField createPasswordField;
    private javax.swing.JLabel createPasswordLabel;
    private javax.swing.JButton createProfileButton;
    private javax.swing.JButton createProfileFromLoginButton;
    private javax.swing.JPanel createProfilePanel;
    private javax.swing.JButton createProfileSubmitButton;
    private javax.swing.JTextField createSecurityAnswerField;
    private javax.swing.JTextField createSecurityQuestionField;
    private javax.swing.JLabel createSecurityQuestionLabel;
    private javax.swing.JTextField createUsernameField;
    private javax.swing.JLabel createUsernameLabel;
    private javax.swing.JTextField deletePasswordField;
    private javax.swing.JLabel deletePasswordLabel;
    private javax.swing.JButton deleteProfileButton;
    private javax.swing.JPanel deleteProfilePanel;
    private javax.swing.JTextField deleteProfileSecurityAnswerField;
    private javax.swing.JLabel deleteProfileSecurityQuestionLabel;
    private javax.swing.JLabel deleteSecurityQuestionLabel;
    private javax.swing.JTextField deleteUsernameField;
    private javax.swing.JLabel deleteUsernameLabel;
    private javax.swing.JButton displayNameChangeButton;
    private javax.swing.JLabel displayNameChangeDisplayNameLabel;
    private javax.swing.JPanel displayNameChangePanel;
    private javax.swing.JTextField displayNameChangePasswordField;
    private javax.swing.JLabel displayNameChangePasswordLabel;
    private javax.swing.JLabel displayNameChangeUsernameLabel;
    private javax.swing.JPanel gamePanel;
    private javax.swing.JPanel gameSettingsPanel;
    private javax.swing.JButton goToLoginButton;
    private javax.swing.JButton goToProfileButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JLabel leaderboardLabel;
    private javax.swing.JPanel leaderboardPanel;
    private javax.swing.JTextField levelSelectionField;
    private javax.swing.JLabel levelSelectionLabel;
    private javax.swing.JButton logOutButton;
    private javax.swing.JPanel loginPanel;
    private javax.swing.JLabel loginStatusLabel;
    private javax.swing.JButton loginSubmitButton;
    private javax.swing.JButton mainMenuButton;
    private javax.swing.JPanel mainMenuPanel;
    private javax.swing.JButton mainMenuViewStatisticsButton;
    private javax.swing.JLabel maxLevelReachedLabel;
    private javax.swing.JPanel modificationPanel;
    private javax.swing.JButton modifyProfileButton;
    private javax.swing.JLabel nameDisplayLabel;
    private javax.swing.JLabel noUsernameLabel;
    private javax.swing.JButton passwordChangeButton;
    private javax.swing.JTextField passwordChangeNewPasswordField;
    private javax.swing.JLabel passwordChangeNewPasswordLabel;
    private javax.swing.JPanel passwordChangePanel;
    private javax.swing.JTextField passwordChangePasswordField;
    private javax.swing.JLabel passwordChangePasswordLabel;
    private javax.swing.JTextField passwordChangeUsernameField;
    private javax.swing.JLabel passwordChangeUsernameLabel;
    private javax.swing.JPasswordField passwordField;
    private java.awt.Label passwordLabel;
    private javax.swing.JLabel personalStatsLabel;
    private javax.swing.JPanel personalStatsPanel;
    private javax.swing.JButton playGameButton;
    private javax.swing.JLabel playerLabel;
    private javax.swing.JLabel profileCreateStatusLabel;
    private javax.swing.JButton profileDeleteButton;
    private javax.swing.JLabel profileDeleteStatusLabel;
    private javax.swing.JPanel profileManagementPanel;
    private javax.swing.JButton startGameButton;
    private javax.swing.JTabbedPane statisticsPanel;
    private javax.swing.JPanel topMenuButtonPanel;
    private javax.swing.JTextField usernameField;
    private java.awt.Label usernameLabel;
    // End of variables declaration//GEN-END:variables
}
