/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package pacmanprogram;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Font;
import java.awt.event.ActionEvent;

/**
 *
 * @author ChanWoo
 * @author stavy92
 * 
 * ScoreDisplay class calculates and display the score of current user
 * on the game play GUI.
 * 
 */
public class ScoreDisplay {
    
    private static final int DOT_POINTS = 10;
    private static final int E_POINTS = 50;
    
    private int score;
    private int totalScore;
    private int dotCount;
    private int energizerCount;
    private int bonusScore;
    private int ghostScore;
    
    private int prevLevel;
    
    Font font = new Font ("Monospaced", Font.BOLD, 20);
    private Color color = Color.WHITE;
    
    Level level;
    
    /**
     * 
     */
    public ScoreDisplay(Level level){
        this.level = level;
        this.totalScore = 0;
    }
    
    /**
     * This method sums all different kinds of scores
     */
    public void getScore(){
        score = getDotScore() + getEnergizerScore() + getBonusScore() + getGhostScore();
    }
    
    
    /**
     * 
     * This method displays the calculated scores on the game play GUI
     * The displayed score keeps being updated as pacman eats different
     * kind of score sources
     * 
     * @param g It is for the 2D-graphic drawings
     */
    public void drawScore(Graphics g){
        getScore();
        Graphics2D score = (Graphics2D) g;
        score.drawString(""+(this.score+totalScore), 10, 35);
    }
    
    public void refresh(ActionEvent ae){
        dotCount = level.getDotsEaten();
        energizerCount = level.getEnergizersEaten();
        
        //calculates socre generated by pacman eating bonus symbols
        bonusScore = level.bonusControl.getBonusesEaten()*level.bonusControl.bonus1.getPoints();
        ghostScore = level.getGhostScore();
    }
    
    public void newLevel(){
        totalScore += score;
    }
    
    /**
     * If new game round is started, this method resets all the score parameters
     * so that it starts from the 0
     */
    public void newGame(){
        dotCount = 0;
        energizerCount = 0;
        bonusScore = 0;
        ghostScore = 0;
        score = 0;
        totalScore = 0;
    }  
    
    /**
     * 
     * @return total score which is the sum of all different kinds of scores
     */
    public int getTotalScore(){
        return (totalScore+score);
    }
    
    /**
     * Calculates the score generated by pacman eating small dots
     * @return score of dot: point per small dot multiplied by number of dots eaten by pacman
     */
    private int getDotScore(){
        return dotCount*DOT_POINTS;
    }
    
    /**
     * Calculates the score generated by pacman eating energizer (big dot)
     * @return score of energizer: point per energizer multiplied by number of energizer eaten by pacman
     */
    private int getEnergizerScore(){
        return energizerCount*E_POINTS;
    }
    
    
    private int getBonusScore(){
        return bonusScore;
    }
    
    private int getGhostScore(){
        return ghostScore;
    }
}
